services:
  api:
    build:
      context: ./api/ 
      dockerfile: Dockerfile.dev
    container_name: starkbank-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - /app/.venv
      - /app/__pycache__
      - /app/**/__pycache__
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: 