services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: starkbank-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
      - /app/__pycache__
      - /app/**/__pycache__
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 