FROM python:3.9-slim

WORKDIR /app

ENV ENVIRONMENT=development

RUN apt-get update && apt-get install -y curl

ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

COPY requirements.txt .

RUN /root/.local/bin/uv pip install -r requirements.txt --system

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 